import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import Script from 'next/script';


export default function Home(props) {


  const [userInput, setUserInput] = useState('')
  const [todoList, settodoList] = useState([])

  useEffect(() => {
   
    getTodos()
  }, [])

  const getTodos = async() => {
    const {data} = await axios.get("/api/todos");
    console.log(data)
    settodoList(data.data)
  }


  const addTodo = async (todo) => {
    if(!todo) {
      alert("Input is empty")
      return
    }
    await axios.post("/api/todos/add", {
      text: todo
    })
  }

  const handleChange = (e) => {
    e.preventDefault()

    setUserInput(e.target.value)
  }

  const handleSubmit = async (e) => {
    e.preventDefault()

    await addTodo(userInput)
    await getTodos()

    setUserInput('')

  }

  const handleDelete = async (id) => {
   await axios.post(`/api/todos/delete?id=${id}`)
   await getTodos()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Script src="https://kit.fontawesome.com/e986a2e970.js" crossorigin="anonymous" async></Script>
        <h1 className={styles.heading}>Todo List</h1>
        <div className={styles.todolist}>
          <form className={styles.flexRow}>
            <input className={styles.inputTodo} type="text" placeholder='Add To-dos' value={userInput} onChange={handleChange}/>
            <button className={styles.btn} onClick={handleSubmit}><i class="fa-solid fa-square-plus fa-2x"></i></button>
          </form>

          <ul className={styles.inputList}>
            <div className={styles.flexCol}>
            {
              todoList.length >=1 ? todoList.map((todo) => {
                return <li className={styles.flexRow} key={todo.id}> {todo.text}<button className={styles.btn} onClick={(e) => {
                  e.preventDefault()
                  handleDelete(todo.id)
                }}><i class="fa-solid fa-trash-can fa-2x"></i></button></li>
              })
              : ""
            }
            </div>
          </ul>
          </div>
      </main>
    </>
  )
}
