import Head from 'next/head'
import { useState } from 'react'
import styles from '@/styles/Home.module.css'


export default function Home() {



  const [userInput, setUserInput] = useState('')
  const [todoList, settodoList] = useState([])

  const handleChange = (e) => {
    e.preventDefault()

    setUserInput(e.target.value)
  }

  const handleSubmit = (e) => {
    e.preventDefault()

    console.log(todoList)

    settodoList([
      userInput,
      ...todoList
    ])

    setUserInput('')

  }

  const handleDelete = (todo) => {
    const updatedArr = todoList.filter(todoItem => todoItem.indexOf(todoItem) !== todoList.indexOf(todo))

    settodoList(updatedArr)
    console.log(updatedArr)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://kit.fontawesome.com/e986a2e970.js" crossorigin="anonymous"></script>
      </Head>
      <main className={styles.main}>
        <h1 className={styles.heading}>Todo List</h1>
        <div className={styles.todolist}>
          <form className={styles.flexRow}>
            <input className={styles.inputTodo} type="text" placeholder='Add To-dos' value={userInput} onChange={handleChange}/>
            <button className={styles.btn} onClick={handleSubmit}><i class="fa-solid fa-square-plus fa-2x"></i></button>
          </form>

          <ul className={styles.inputList}>
            <div className={styles.flexCol}>
            {
              todoList.length >=1 ? todoList.map((todo, idx) => {
                return <li className={styles.flexRow} key={idx}> {todo}<button className={styles.btn} onClick={(e) => {
                  e.preventDefault()
                  handleDelete(todo)
                }}><i class="fa-solid fa-trash-can fa-2x"></i></button></li>
              })
              : ""
            }
            </div>
          </ul>
          </div>
      </main>
    </>
  )
}
